general:
  code: "<Enter your project's code (5 chars) here>"
  not-so-secret-keyword: "<Enter your not-so-secret keyword here>"
# Следующий ниже раздел определяет, кто может подключаться к серверу, а кто нет.
# Если какие-то настройки удалены, значения allow по умолчанию имеют только: project, voxile.
# Также значения по умолчанию не содержат никаких названий особых групп.
players:
  # Если сервер находится в offline-mode, то под данную категорию попадают без исключения все игроки.
  # Если сервер находится в online-mode, то под данную категорию попадут лицензионные игроки, использующие
  # официальный (либо любой другой, отличный от Voxile) лаунчер.
  no-launcher:
    # Разрешает вход на сервер соответствующей категории игроков
    allow: true
    # Опционально: укажите группу, которой будут принадлежать игроки, попадающие под данную категорию.
    # Оставьте поле пустым (''), чтобы не назначать указанным игрокам специальную группу.
    special-group: ''
  # Под данную категорию попадают игроки, нажавшие в лаунчере кнопку "Гостевой вход".
  # Только для сервера, работающего в режиме online-mode.
  guest:
    # Разрешает вход на сервер соответствующей категории игроков
    allow: true
    # Опционально: укажите группу, которой будут принадлежать игроки, попадающие под данную категорию.
    # Оставьте поле пустым (''), чтобы не назначать указанным игрокам специальную группу.
    special-group: ''
  # Под данную категорию попадают игроки, вошедшие с использованием лицензионной учётной записи Mojang.
  # Только для сервера, работающего в режиме online-mode.
  license:
    # Разрешает вход на сервер соответствующей категории игроков
    allow: true
    # Опционально: укажите группу, которой будут принадлежать игроки, попадающие под данную категорию.
    # Оставьте поле пустым (''), чтобы не назначать указанным игрокам специальную группу.
    special-group: ''
  # Под данную категорию попадают игроки, использовавшие пару логин-пароль с сайта/форума/блога проекта,
  # которому принадлежит данный сервер.
  # Только для сервера, работающего в режиме online-mode.
  project:
    # Разрешает вход на сервер соответствующей категории игроков
    allow: true
    # Опционально: укажите группу, которой будут принадлежать игроки, попадающие под данную категорию.
    # Оставьте поле пустым (''), чтобы не назначать указанным игрокам специальную группу.
    special-group: ''
  # Под данную категорию попадают игроки, использовавшие пару свою учётную запись на http://voxile.ru
  # Только для сервера, работающего в режиме online-mode.
  voxile:
    # Разрешает вход на сервер соответствующей категории игроков
    allow: true
    # Опционально: укажите группу, которой будут принадлежать игроки, попадающие под данную категорию.
    # Оставьте поле пустым (''), чтобы не назначать указанным игрокам специальную группу.
    special-group: ''
  # К сожалению, авторизоваться в лаунчере с использованием VK на данный момент нельзя.
  # Только для сервера, работающего в режиме online-mode.
  #vk:
    # Разрешает вход на сервер соответствующей категории игроков
    #allow: true
    # Опционально: укажите группу, которой будут принадлежать игроки, попадающие под данную категорию.
    # Оставьте поле пустым (''), чтобы не назначать указанным игрокам специальную группу.
    #special-group: ''
internal:
  version: 1
