general:
  # Possible values: mojang (mojang.com), ely.by (ely, minecraft.ely.by), methuselah.ru (methuselah, auth.methuselah.ru), custom
  links-provider: methuselah
  # Enable debug mode?
  debug: false
methuselah:
  # Unique project code
  code: "<Enter your project's code (5 chars) here>"
  # That random chars from Web UI
  not-so-secret-keyword: "<Enter your not-so-secret keyword here>"
internal:
  version: 1
